name: Update Vibe Badge

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  update:
    if: "!contains(github.event.head_commit.message, '[skip vibe-badge]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Vibe Coded Badge
        uses: trieloff/vibe-coded-badge-action@main